# Test profile for logging functionality without PKCS#11 dependencies
spring:
  profiles:
    active: logging-test

# Logging configuration
logging:
  level:
    com.example.pkcs11: INFO
    org.springframework: WARN
    root: INFO
  file:
    name: application.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# Server configuration
server:
  port: 8085

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,loggers
  endpoint:
    health:
      show-details: always