server:
  port: 8085

spring:
  application:
    name: pkcs11-signing-service

# PKCS#11 Configuration
pkcs11:
  library: ${PKCS11_LIBRARY:/usr/lib64/softhsm/libsofthsm.so}
  slot: ${PKCS11_SLOT:-1}
  provider-name: ${PKCS11_PROVIDER_NAME:SoftHSM-Provider}
  pin: ${PKCS11_PIN:1234}

# Logging configuration
logging:
  file:
    name: __logs/application.log
  level:
    com.example.pkcs11: INFO
    org.springframework.security: WARN
    root: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
