# Development configuration using SoftHSM2
pkcs11:
  library: /usr/local/lib/softhsm/libsofthsm2.so
  slot: 0
  provider-name: SoftHSM-Provider
  pin: 1234

# Enhanced logging for development
logging:
  level:
    com.example.pkcs11: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# Development server configuration
server:
  port: 8085
  error:
    include-stacktrace: always
    include-message: always

# Management endpoints for development
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always